baseURL: https://financefasttrack.netlify.app/
languageCode: en-us
title: Finance Fast Track
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      The Express Guide to Markets.
    title: Welcome to Finance Fast Track
  blog: {}
  contact:  
    address:
      - city: London, SW15 5JS
        country: United Kingdom
        street: 12 Roehampton Gate
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mariopucinelli.fft@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (044) 7518 404900
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Finance Fast Track
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
      #- icon: fa-instagram
        #label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/MPucinelli
      - icon: fa-linkedin
        label: LinkedIn
        url: https://linkedin.com/in/mario-pucinelli-filho
  image: pic02.jpg
  name: Mario Pucinelli Filho
  navigation:
    #button1:
      #- name: Get Started
        #url: blogs
    #button2:
      #- name: Log In
        #url: '#'
    links:
      - name: Home
        url: 'pie'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
        #url: elements.html
    menu: Menu
    subtitle: By Mario Pucinelli Filho
    title: FFT
  tiles:
    enable: yes
    showcase:
      - image: lbspic.jpg
        subtitle: How did we get here??
        title: Founder's Story
        url: blogs/My_Story 
      - image: fftpicco.jpg
        subtitle: Check out one of our issues!
        title: Sample Issues
        url: blogs/sample_issue
      - image: codycody.jpg
        subtitle: How R can be a Powerful Tool
        title: Coding is the Future
        url: blogs/citf
      - image: job.jpg
        subtitle: Compare your CV with ours first!
        title: Looking for work?
        url: blogs/cv
      #- image: pic05.jpg
        #subtitle: Ipsum Dolor Sit Amet
        #title: Consequat
        #url: blogs/ipsum
      #- image: pic06.jpg
        #subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
  two:
    #buttonText: Get Started
    enable: yes
    subtitle: "We aim to consolidate information from both international and local news sources, examining the impact of global events
through the domestic lenses of the countries which we cover."
    title: Our Mission
    #url: blogs
